# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-01 04:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_device_hornlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='aadhar',
            new_name='UID',
        ),
    ]
