# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-02 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170401_0434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=10)),
                ('password', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SensitivePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_x', models.CharField(default='', max_length=20)),
                ('location_y', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='regNum',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='device',
            name='agent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.Agent'),
        ),
    ]
