# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-02 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170402_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='agent',
        ),
    ]
