# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-02 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_device_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_x', models.CharField(default='', max_length=20)),
                ('location_y', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
