# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-02 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_indices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
